services:
  bot:
    image: node:22-alpine
    container_name: discord_bot
    working_dir: /usr/src/app
    restart: always
    volumes:
      - ./:/usr/src/app   # 현재 프로젝트 디렉토리를 컨테이너에 마운트
      - /usr/src/app/node_modules  # node_modules는 호스트에 영향 안 주도록
    env_file:
      - .env   # 환경변수 파일
    command: sh -c "npm install && npm run start"
    networks:
      - home_net

networks:
  home_net:
    external: true